name: Hello World

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: | 
            python -m pip install --upgrade pip
            pip install flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: execute py script # run file
        run: |
          python hello_world.py

  job2:
    needs: [ job1 ]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: helloworld.arft
          path: . 
          
